### ISSUE TITLE
License

### ISSUE THREAD

**Issue by marado** [ResearchHub/researchhub-web#1]
Hi there!

I arrived here after reading this tweet: https://twitter.com/ResearchHub/status/1394111807774765062?s=19

Congratulations on your decision to open your source!

Unfortunately, you're not there yet. I see nothing on this repository indicating it is Open Source: no license on the README, no License file, no license on package.json or in the header of the actual code files.

**Comment by lightninglu10** [comment]
Whoops, now resolved!
