### ISSUE TITLE
Search Auto-suggest

### ISSUE THREAD

**Issue by yattias** [ResearchHub/researchhub-web#1081]
### What?
Implement search "auto-suggest" / typeahead. From a UX perspective, entering a few characters in the search field should display a mixed set of results: People, papers, posts, hubs, hypotheses. V2 of this feature would also include comments.

This bounty does not include any frontend work.

### How?
The most promising solution based on good amount of research is using Elastic Search's Suggester feature. https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html.

The right solution should utilize package https://github.com/barseghyanartur/django-elasticsearch-dsl-drf which supports suggesters.

ℹ️  It is possible that using suggesters is not the right course of action. As the person implementing this feature, if you think of an alternative, please suggest it to the team and get approval first.

### About Search
- Chat with @yattias (Kobe Attias) on discord before implementing this feature in order to get get an overview of this feature

### Important
Please keep in close loop with the RH team as you develop this feature. We strive for all assigned bounties to be merged successfully and want to avoid a scenario in which we do not do so due to poor quality or unacceptable implementation choices.

### Acceptance Criteria
- Endpoint which will be used by FE to fetch mixed content (posts, hubs, hypotheses, people). 
   - Endpoint should require at least three characters to return results  
   - Note: Do not create separate endpoints for each document type. Rather, create one endpoint for all mixed content
   - See how "best results" works as an example https://www.researchhub.com/search/all?q=crypto
-  Automatically indexing of content into Elastic Search Suggester data structure
   - Note: We already have automatic indexing of content, we should be able to piggyback off of that
- Speed. Since the feature is auto-suggest
- Unit tests that cover basic functionality of the feature
- Documentation about how to use the feature

### Bounty Completion Requirements
- Explicit approval by a member of the RH team is required before starting work
- Verified and merged code is required in order to earn the assigned bounty

![image](https://user-images.githubusercontent.com/802819/150263780-05e3ea45-0e5a-448a-8032-f72d22b83db3.png)

**Comment by ef3n9r98** [comment]
Hi @yattias , I know some devs who'd be interested in working on this. If the issue's not too old, how much is the bounty for this issue?

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!
