### ISSUE TITLE
Render arxiv Preprints as HTML

### ISSUE THREAD

**Issue by yattias** [ResearchHub/researchhub-web#1112]
### What
Render arxiv preprints as HTML by integrating with https://ar5iv.labs.arxiv.org/ or similar alternative. 

The above is an alternative / supplement to PDF extraction. Our PDF extraction mechanism has the following issues
1. Formulas and equations do not extract properly. These typically render as odd unicode characters.
2. Figures such as graphs and images do not extract properly. 

The above issues lead to bad UX and reduced confidence in the content of the paper. Due to this, many users leave ResearchHub and read the paper externally. As a result, we turned off the PDF extraction.

The ar5iv project can allow us to render preprints as HTML which can help add a lot of value to RH given that arxiv does not offer good reading UX. In addition, rendering content as HTML will help us achieve inline highlighting.

### Acceptance Criteria
- Visiting a paper page which includes a PDF should render the PDF content as HTML
- Mathematical equations and figures should render properly

### Important
- There is an endpoint `pdf_extract` in `paper/views` which fetches extracted content.

**Comment by smrutiparida** [comment]
Hi. I am interested to take up the work. Before doing that, I wanted to check on how the bounty works ? What is the bounty amount, how shall you pay for the same and how to ensure that payment shall happen once work is completed .
