### ISSUE TITLE
Match Component heights in Home page to make it look more professional

### ISSUE THREAD

**Issue by calvinhlee23** [ResearchHub/researchhub-web#1160]
<img width="1789" alt="Screen Shot 2022-04-12 at 11 12 08 AM" src="https://user-images.githubusercontent.com/17622930/163026876-fbb8588d-ef82-4538-83ea-b87b410931e1.png">

**Comment by andrewpedron** [comment]
@calvinhlee23 Does this still need work or can we archive?
