### ISSUE TITLE
[Feature Request] - Share to Twitter button w/formatting

### ISSUE THREAD

**Issue by TylerDiorio** [ResearchHub/researchhub-web#1373]
**Problem**: 
Sharing to social media from ResearchHub is not built-in and difficult to show content.

**Objective**:
Quickly share highlights from research papers or posts/comments you've made on ResearchHub

**Readwise Solution:**
Pre-built formatting for Twitter style posts that show your material in an image preview on socials & built-in share button on ResearchHub posts

**User stories:**
Eleanor: Being able to quickly “share” the ResearchHub content via Twitter/other with a plug-in would assist in making references to ResearchHub on her YouTube videos easier. This allows her to seamlessly take content from Readwise directly to her socials and she wishes this was the case for ResearchHub.

**Minimum Features:**
Share to Twitter + Readwise style cards

**(1)** **Example viewport for social media feeds** _(optional workflow from Reference Manager if  following social groups)_
![Image](https://user-images.githubusercontent.com/109099227/233669998-80162cfe-4584-4e64-a386-581772dde5dc.png)

Ideally you would be able to right-click share like as in the screenshot below:
![Image](https://user-images.githubusercontent.com/109099227/233674825-26362d57-caed-49b9-bb72-105504457b21.png)

**(2)** **Primary feature we should target: quick sharing highlights from content** - in this case the content we're sharing is a highlight from a Tweet but this would work the same from a highlighted text in a PDF
![Image](https://user-images.githubusercontent.com/109099227/233670036-fb1a721a-62b4-446c-bb96-4a9301b977e5.png)

**(3)** **Alternate formatting options are great**
![Image](https://user-images.githubusercontent.com/109099227/233670393-304933ac-5142-48f7-8563-06a9d83ae451.png)

**(4) Alternative platforms for sharing these quick grabs:**
![Image](https://user-images.githubusercontent.com/109099227/233670924-56a752d4-870b-4f68-894f-4f8e10a3cd7f.png)

How this could look for ResearchHub:
![Image](https://user-images.githubusercontent.com/109099227/233690100-42de5793-56a6-47aa-ab65-dc47d7c78876.png)

(Alt purple)
![Image](https://user-images.githubusercontent.com/109099227/233690483-e40faf2c-a040-471e-ba3d-defb2fc970be.png)

(Alt gray)
![Image](https://user-images.githubusercontent.com/109099227/233690380-f96cde4f-279c-4978-9587-bab8dbba0737.png)

(Alt bland)
![Image](https://user-images.githubusercontent.com/109099227/233690168-2eb32990-3992-45ad-8bee-5c69c21ffea5.png)

**Comment by yattias** [comment]
We do need something like this. I'll take this one in the next sprint or two. We need the ability to share to twitter and in general

**Comment by TylerDiorio** [comment]
@yattias Ok great, thanks Kobe - and if you'd like any more detail on the workflow idea I put above, I can happily gather more user feedback

**Comment by TylerDiorio** [comment]
Just added some mock-ups for what our posts could look like - trying to give a good preview of the content, adding my personal favorite style below:


![Image](https://user-images.githubusercontent.com/109099227/233690819-35227e12-66d3-4aea-9c72-f44f892136ec.png)

**Comment by yattias** [comment]
Thank you @TylerDiorio that is very helpful
