### ISSUE TITLE
Live Feed Redesign

### ISSUE THREAD

**Issue by yattias** [ResearchHub/researchhub-web#1397]
This issue will include design requirements for the next iteration of the live feed. Everyone is able to participate and provide feedback.

**Comment by bluefoxxy** [comment]
https://www.figma.com/file/znA48J1Q1BSG9FnleK1ejZ/Live-view-V2?type=design&node-id=1705%3A22120&t=PJJENDEh7YCZAhpv-1

**Comment by bluefoxxy** [comment]
https://www.notion.so/Live-Feed-V2-56387fc915cd4674b7f09843d400c319 - Link to one pager
