### ISSUE TITLE
Edit Abstract visual bug

### ISSUE THREAD

**Issue by lightninglu10** [ResearchHub/researchhub-web#1512]
1. pencil icon is showing in a weird spot when abstract is blank
2. no save button (need to scroll) when abstract is long

![Image](https://user-images.githubusercontent.com/2453737/253128040-c648a3d7-cb33-478a-b8a6-34a5b9052375.png)
![Image](https://user-images.githubusercontent.com/2453737/253128041-7ec15ac6-af7e-4385-96b7-24cd5a6b7154.png)

**Comment by yattias** [comment]
Nice, thanks for putting it in here
