### ISSUE TITLE
Download file prompt when opening specific paper pages

### ISSUE THREAD

**Issue by yattias** [ResearchHub/researchhub-web#1513]
From Jeff
When I first click onto a paper OR when I click on the "paper" tab it will automatically download the paper's PDF to my local drive. Here's the paper it is happening on: https://www.researchhub.com/paper/1277194/efficacy-of-mrna-1273-and-novavax-ancestral-or-ba1-spike-booster-vaccines-against-sars-cov-2-ba5-infection-in-non-human-primates
2023-07-13T00:09:52.348000+00:00

**Comment by le-sun** [comment]
From the database:
https://www.science.org/doi/pdf/10.1126/sciimmunol.adg7015?download=true
