### ISSUE TITLE
Z-index issue (comment shows above header)

### ISSUE THREAD

**Issue by yattias** [ResearchHub/researchhub-web#1733]
Picture worth a thousand words
https://www.researchhub.com/post/2170/anonymity-in-peer-review

![image](https://github.com/ResearchHub/researchhub-web/assets/802819/bca1d7d3-d722-4944-ab82-30e5d9b9e73f)

**Comment by SandipGyawali** [comment]
hey @yattias i wanna work on it can you assign it to me ?

**Comment by yattias** [comment]
@SandipGyawali feel free to work on and open a PR. We usually don't assign Open Source issues

**Comment by yattias** [comment]
Moved to https://github.com/ResearchHub/issues/issues/3

**Comment by yattias** [comment]
@SandipGyawali Have you taken a look?
