### ISSUE TITLE
Editing a post requires re-selecting hub

### ISSUE THREAD

**Issue by yattias** [ResearchHub/researchhub-web#1737]
1. Click edit post
2. Click republish
3. You will see the hub is missing title. You will need to x out of it and reenter the hub associated with the post

![Image](https://github.com/ResearchHub/researchhub-web/assets/802819/d27a4887-d24f-4ca6-9c80-0cb5acf7cb20)

**Comment by dominikusbrian** [comment]
Noticed this issue some time back. A bit annoying since I have several posts I want and tried to update regularly.
Would love to contribute with this as my first issue. Any directive on where to start experimenting ?

**Comment by yattias** [comment]
Issue moved to: https://github.com/ResearchHub/researchhub-web/issues/1737
